name: choira_task
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0+1 #for animations
  google_fonts: ^6.1.0 #external fonts
  intl_phone_field: ^3.2.0 #phone textfield
  flutter_otp_text_field: ^1.1.1 #otp textfield
  timer_count_down: ^2.2.2 #timer

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
